### ISSUE TITLE
[Crash] On Create New Game

### ISSUE THREAD

**Issue by Sweek9** [Dremoline/PortableTanks#8] opened 2023-11-10 06:29 UTC
**Version info**
- Minecraft v1.20.2
- Portable Tanks v1.1.7
- Forge v48.0.35
- SuperMartijn642's Core Lib v1.1.15a
- SuperMartijn642's Config Lib v1.1.8
- Formations v1.0.1

**Steps to reproduce**
"Singleplayer"
"Create New Game"
I was crashing this exact same way with SuperMartijn642's Formations mods. Like those, your mod does not list any dependencies on the CurseForge page, and the log does not indicate which mod is causing it. However at least you correctly (I assume) marked the dependencies it has with Forge; SuperMartijn642's Core + Config Libs, prompting me to get them upon launch. It's just that the crash occurs with them installed. 
The solution I found with his mods (after hours of debugging) was installing the hidden dependency, a library called Formations. However that did not work in this case. Perhaps you're also hiding a dependency that I wasn't able to find?

**Crash report (~/logs/latest.log)** 
[latest.log](https://github.com/Dremoline/PortableTanks/files/13316243/latest.log)

**Comment by SuperMartijn642** [comment] 2023-11-10 09:18
![image](https://github.com/Dremoline/PortableTanks/assets/12382965/1b1e4f3b-b88b-4f85-8497-3a9d6493a829)
![image](https://github.com/Dremoline/PortableTanks/assets/12382965/ea5e48f1-dcce-4279-bcd1-3539df163996)
![image](https://github.com/Dremoline/PortableTanks/assets/12382965/bff0092c-b829-494d-a330-3822cb5f5ec1)

**Comment by Sweek9** [comment] 2023-11-14 18:41
You seem to have misunderstood my message. Please see the "Version info" section to see the list of mods installed at the time the crash occurs. The crash occurs **with** those listed dependencies installed. Since an identical crash occurred in a **different** mod without a dependency (which was not marked as required **inside Forge's mod loader** with those **other** mods only; nor were dependencies listed in the **Description section** on CurseForge for those other mods nor this one), my question was whether this mod has **additional** required dependencies besides those 2 that are not listed. If not then I suppose it's a fatal bug in the mod.

**Comment by SuperMartijn642** [comment] 2023-11-14 19:34
Indeed, I assumed this was the same issue as with the two issues you created for the Formations mods. This crash is caused by changes in Minecraft 1.20.2 compared to 1.20.1 and the mod will need to be updated to fix it.

> nor were dependencies listed in the Description section on CurseForge for those other mods nor this one

About the dependencies, CurseForge has a dedicated page for them. I am not going to put the dependencies in the description when there's an entire tab for them just one click away.

**Comment by Dremoline** [comment] 2023-12-05 22:01
Hey, 
Should be fixed in the new update.

**Closed as completed by Dremoline** 2023-12-05 22:01 UTC
