### ISSUE TITLE
[Bug] Pulling fluids from tank w/ stacked buckets

### ISSUE THREAD

**Issue by Khalelyk** [Dremoline/PortableTanks#2] opened 2021-11-22 12:43 UTC
**Version info**
Minecraft 1.17.1
portabletanks-1.1.1-mc1.17.jar

**Describe the bug**
Right-clicking tanks with a stack of buckets does nothing, must separate buckets to pull out of tank

**Comment by Dremoline** [comment] 2021-12-01 23:52
Hey,
The issue is fixed in version 1.1.2. Thanks for reporting the bug!

**Closed as completed by Dremoline** 2021-12-01 23:52 UTC
Labels: bug
