### ISSUE TITLE
[Bug] Portable Tanks not compatible with SuperMartijn642's Core Lib 1.1.0

### ISSUE THREAD

**Issue by ScottDTA** [Dremoline/PortableTanks#7] opened 2023-01-03 22:10 UTC
**Version info**
Minecraft 1.18.2
Portable Tanks 1.1.6

Is not compatible with the latest version of SuperMartijn642's Core Lib, version 1.1.0

**Comment by Gbergz** [comment] 2023-01-09 19:05
Can confirm this issue.
Edit: On 1.19.2 & 1.18.2

**Comment by ALainxD** [comment] 2023-02-02 17:25
Is there a solution to this?

**Comment by MrFreakOne** [comment] 2023-02-04 18:48
Hello,  **(It was translated into English with Google Translate.)**

![BI-01](https://user-images.githubusercontent.com/53281959/216784344-862f9289-11f8-4861-8782-ebba135648d5.jpg)

i get the same error messages as described above. For me the Minecraft version is 1.16.5. It wants SuperMartijn642's Core Lib v1.1.1

See You.

**Comment by SuperMartijn642** [comment] 2023-02-04 19:55
Portable Tanks' dependency on my core library is simply set to only accept versions below 1.1.0. This is intentional as version 1.1.0 of my core library has many breaking changes.
I help @Dremoline with the coding part of Portable Tanks, so we have to find a time where we're both available. As we are both quite busy, updating takes a bit.

**Comment by MrFreakOne** [comment] 2023-02-04 20:18
Hello,  **(It was translated into English with Google Translate.)**

**@SuperMartijn642**

this answer is enough for me. Just knowing that you guys are working on it and that there will be an upgrade at some point is enough for me. Thank you for your work and time (and for the quick reply). This is not always a matter of course.   👍

See You.  :) :) :)

**Comment by Dremoline** [comment] 2023-06-18 20:16
Hey, the issue is resolved in the new update we just released. Let us know if you encounter more problems.

**Closed as completed by Dremoline** 2023-06-18 20:16 UTC
Labels: bug
